CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                       NVARCHAR (450)     NOT NULL,
    [FirstName]                NVARCHAR (16)      NOT NULL,
    [LastName]                 NVARCHAR (16)      NOT NULL,
    [Address]                  NVARCHAR (MAX)     NULL,
    [AddressLine1]             NVARCHAR (MAX)     NULL,
    [AddressLine2]             NVARCHAR (MAX)     NULL,
    [City]                     NVARCHAR (MAX)     NULL,
    [State]                    NVARCHAR (MAX)     NULL,
    [ZipCode]                  NVARCHAR (MAX)     NULL,
    [CompanyName]              NVARCHAR (MAX)     NULL,
    [BusinessDuration]         INT                NULL,
    [HearAboutUs]              NVARCHAR (MAX)     NULL,
    [AcceptAgreement]          BIT                NOT NULL,
    [UserName]                 NVARCHAR (256)     NULL,
    [NormalizedUserName]       NVARCHAR (256)     NULL,
    [Email]                    NVARCHAR (256)     NULL,
    [NormalizedEmail]          NVARCHAR (256)     NULL,
    [EmailConfirmed]           BIT                NOT NULL,
    [PasswordHash]             NVARCHAR (MAX)     NULL,
    [SecurityStamp]            NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]         NVARCHAR (MAX)     NULL,
    [PhoneNumber]              NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed]     BIT                NOT NULL,
    [TwoFactorEnabled]         BIT                NOT NULL,
    [LockoutEnd]               DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]           BIT                NOT NULL,
    [AccessFailedCount]        INT                NOT NULL,
    [IntrestedIn]              NVARCHAR (MAX)     NULL,
    [IsBasicUser]              BIT                NOT NULL,
    [IsBroker]                 BIT                NOT NULL,
    [IsBuyer]                  BIT                NOT NULL,
    [IsLender]                 BIT                NOT NULL,
    [IsTransactionCoordinator] BIT                NOT NULL,
    [OfficePhone]              NVARCHAR (20)      NULL,
    [PrimaryRole]              NVARCHAR (50)      NULL,
    [ProfilePicName]           NVARCHAR (MAX)     NULL,
    [RoleType]                 NVARCHAR (50)      NULL,
    [Title]                    NVARCHAR (50)      NULL,
    [CreatedDate]              DATETIME           NULL,
    [UpdatedDate]              DATETIME           NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);



