CREATE TABLE [dbo].[Lender] (
    [LenderId]                                   INT            IDENTITY (1, 1) NOT NULL,
    [UserId]                                     NVARCHAR (450) NOT NULL,
    [FirstName]                                  NVARCHAR (16)  NULL,
    [LastName]                                   NVARCHAR (16)  NULL,
    [Email]                                      NVARCHAR (MAX) NULL,
    [PhoneNumber]                                NVARCHAR (20)  NULL,
    [RoleInLendingCompany]                       NVARCHAR (100) NULL,
    [LenderCompanyName]                          NVARCHAR (100) NULL,
    [EntityType]                                 INT            NULL,
    [LenderPhoneNo]                              NVARCHAR (20)  NULL,
    [Address1]                                   NVARCHAR (500) NULL,
    [Address2]                                   NVARCHAR (500) NULL,
    [City]                                       NVARCHAR (100) NULL,
    [StateId]                                    INT            NULL,
    [ZipCode]                                    NVARCHAR (20)  NULL,
    [Country]                                    NVARCHAR (50)  NULL,
    [YearsInBusiness]                            NVARCHAR (10)  NULL,
    [EstimatedLoansDonePerYear]                  NVARCHAR (10)  NULL,
    [PreferredAttorneyForDocDrafting]            NVARCHAR (MAX) NULL,
    [PreferredAttorneyPhone]                     NVARCHAR (20)  NULL,
    [AttorneyEmail]                              NVARCHAR (MAX) NULL,
    [InterestedInServeLoansRightHereWithInReidy] INT            NULL,
    [ProofType]                                  INT            NULL,
    [IdentificationType]                         INT            NULL,
    [IdentificationFileName]                     NVARCHAR (MAX) NULL,
    [IdentificationFilePath]                     NVARCHAR (MAX) NULL,
    [Disclosure]                                 BIT            NULL,
    [IsSignupCompleted]                          INT            NULL,
    [OfficePhone]                                NVARCHAR (20)  NULL,
    [Title]                                      NVARCHAR (100) NULL,
    CONSTRAINT [PK_Lender] PRIMARY KEY CLUSTERED ([LenderId] ASC),
    CONSTRAINT [FK_Lender_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id])
);

