CREATE TABLE [dbo].[Property] (
    [PropertyId]                            INT             IDENTITY (1, 1) NOT NULL,
    [RelationshipToProperty]                INT             NOT NULL,
    [TargetPrice]                           DECIMAL (18, 2) NOT NULL,
    [Address1]                              NVARCHAR (MAX)  NOT NULL,
    [Address2]                              NVARCHAR (MAX)  NULL,
    [City]                                  NVARCHAR (MAX)  NOT NULL,
    [StateId]                               INT             NOT NULL,
    [ZipCode]                               INT             NOT NULL,
    [BuildingStatus]                        INT             NOT NULL,
    [BuildingCount]                         DECIMAL (18, 2) NULL,
    [Units]                                 INT             NOT NULL,
    [BuiltSquareFootage]                    DECIMAL (18, 2) NULL,
    [Floors]                                INT             NOT NULL,
    [YearBuilt]                             NVARCHAR (MAX)  NULL,
    [YearRenovated]                         NVARCHAR (MAX)  NULL,
    [LandArea]                              DECIMAL (18, 2) NULL,
    [Occupancy]                             NVARCHAR (MAX)  NULL,
    [WillOccupantStayAfterSale]             INT             NOT NULL,
    [Construction]                          INT             NULL,
    [Elevators]                             INT             NOT NULL,
    [ParkingCount]                          DECIMAL (18, 2) NULL,
    [Governance]                            NVARCHAR (MAX)  NULL,
    [ZoningDescription]                     NVARCHAR (MAX)  NULL,
    [DeliveryBays]                          INT             NOT NULL,
    [Highlights]                            NVARCHAR (MAX)  NULL,
    [AcceptUserAgreement]                   BIT             NULL,
    [PropertyTypeId]                        INT             NOT NULL,
    [IsActive]                              BIT             NOT NULL,
    [Status]                                INT             NOT NULL,
    [Latitude]                              NVARCHAR (MAX)  NULL,
    [Longitude]                             NVARCHAR (MAX)  NULL,
    [Description]                           NVARCHAR (MAX)  NULL,
    [ImageName]                             NVARCHAR (MAX)  NULL,
    [CreatedBy]                             INT             NOT NULL,
    [CreatedOn]                             DATETIME2 (7)   NULL,
    [ModifiedBy]                            INT             NOT NULL,
    [ModifiedOn]                            DATETIME2 (7)   NULL,
    [IdentificationVarificationId]          INT             NOT NULL,
    [IdentificationFileName]                NVARCHAR (MAX)  NULL,
    [IdentificationFilePath]                NVARCHAR (MAX)  NULL,
    [IsSellerfinancing]                     BIT             NOT NULL,
    [DownPaymentNeeded]                     DECIMAL (18, 2) NULL,
    [InterestBeingOffered]                  DECIMAL (18, 2) NULL,
    [TermOfLoanYear]                        INT             NOT NULL,
    [TermOfLoanMonth]                       INT             NOT NULL,
    [Amortized]                             INT             NOT NULL,
    [IsthisaSubjecttoAssumption]            BIT             NOT NULL,
    [CashToCloseNeeded]                     DECIMAL (18, 2) NULL,
    [MortgageBalance]                       DECIMAL (18, 2) NULL,
    [MonthlyPaymentBeingAssumed]            DECIMAL (18, 2) NULL,
    [EscrowsIncludedInMonthlyPayment]       NVARCHAR (MAX)  NULL,
    [TermLeftOnMortgageYear]                INT             NOT NULL,
    [TermLeftOnMortgageMonth]               INT             NOT NULL,
    [AmortizationOfMortgage]                INT             NOT NULL,
    [DueDiligencePeriodAvailableDays]       INT             NOT NULL,
    [OriginalTargetPrice]                   DECIMAL (18, 2) NOT NULL,
    [ResidentialBuildingStatus]             INT             NOT NULL,
    [ResidentialRenovated]                  NVARCHAR (MAX)  NULL,
    [ResidentialAfterRepairValue]           DECIMAL (18, 2) NOT NULL,
    [ResidentialBedrooms]                   INT             NOT NULL,
    [ResidentialBathrooms]                  INT             NOT NULL,
    [ResidentialBuiltSquareFootage]         DECIMAL (18, 2) NOT NULL,
    [ResidentialLotSizeSquareFootage]       DECIMAL (18, 2) NOT NULL,
    [ResidentialBuiltYear]                  INT             NOT NULL,
    [ResidentialRenovatedYear]              INT             NOT NULL,
    [ResidentialParking]                    INT             NOT NULL,
    [ResidentialParkingSpace]               INT             NOT NULL,
    [ResidentialOccupancy]                  INT             NOT NULL,
    [ResidentialWillOccupancyStayAfterSale] INT             NOT NULL,
    [KeyFeature1]                           NVARCHAR (MAX)  NULL,
    [KeyFeature2]                           NVARCHAR (MAX)  NULL,
    [KeyFeature3]                           NVARCHAR (MAX)  NULL,
    [KeyFeature4]                           NVARCHAR (MAX)  NULL,
    [OtherGovernance]                       NVARCHAR (50)   NULL,
    [LandSquareFootage]                     NVARCHAR (100)  NULL,
    [LotStatus]                             INT             NULL,
    [LotUse]                                INT             NULL,
    [Electric]                              INT             NULL,
    [Gas]                                   INT             NULL,
    [Water]                                 NVARCHAR (50)   NULL,
    [OpenToPartneringWithBuilders]          INT             NULL,
    [SurveyAvailable]                       INT             NULL,
    [EnvironmentalAvailable]                INT             NULL,
    [LandSquareFootageUnit]                 INT             NULL,
    CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED ([PropertyId] ASC)
);

